TMG changes
telegraph/acs-aem-commons pull request #1
Opened 2018-03-12 15:56 UTC by james-appleby

Applying the custom features added to the ACS commons library for TMG custom features

2018-03-12 21:21 UTC, mehtarachna commented on bundle/src/main/java/com/adobe/acs/commons/images/CropConstants.java
> +package com.adobe.acs.commons.images;
This class is already in telegraph-components

2018-03-12 21:22 UTC, mehtarachna commented on bundle/src/main/java/com/adobe/acs/commons/images/transformers/impl/ParamCropImageTransformerImpl.java
> +public class ParamCropImageTransformerImpl extends CropImageTransformerImpl {
+1, already in telegraph-components

2018-03-12 21:22 UTC, mehtarachna commented on bundle/src/test/java/com/adobe/acs/commons/images/transformers/impl/ParamCropImageTransformerImplTest.java
> +public class ParamCropImageTransformerImplTest {
+1

2018-03-12 21:25 UTC, mehtarachna requested changes
I think we only need to add NamedImageTransformerServlet & it's unit test class in this acs commons package, rest of the classes are in core.  This work of separating out classes from core and acs commons (so that patch size is minimum with each upgrade) was done before 6.2 but then 6.2 reverted it back due to some unknown reasons.

2018-03-13 09:52 UTC, james-appleby commented on bundle/src/main/java/com/adobe/acs/commons/images/CropConstants.java
> +package com.adobe.acs.commons.images;
Removed

2018-03-13 09:52 UTC, james-appleby commented on bundle/src/main/java/com/adobe/acs/commons/images/transformers/impl/ParamCropImageTransformerImpl.java
> +public class ParamCropImageTransformerImpl extends CropImageTransformerImpl {
Removed

2018-03-13 09:52 UTC, james-appleby commented on bundle/src/test/java/com/adobe/acs/commons/images/transformers/impl/ParamCropImageTransformerImplTest.java
> +public class ParamCropImageTransformerImplTest {
Removed

2018-03-13 12:52 UTC, mehtarachna approved these changes

2018-03-13 12:57 UTC, OlutayoA approved these changes

2018-03-13 13:23 UTC, merged